---
title: "Reference"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>"
)

library(dplyr)
library(pkgdoc)
```

```{r functions, include=FALSE, warning=FALSE}
bank_packages <- paste0("r2dii.", c("data", "match", "analysis"))
lapply(bank_packages, library, character.only = TRUE)

stopifnot(
  all_pkg_must_be_attached = all(
    paste0("package:", bank_packages) %in% search()
  )
)

r2dii_url <- "https://2degreesinvesting.github.io/"

r2dii_reference_concept <- function(x, url = r2dii_url) {
  custom_table(
    reference_concept(
      x, url = url, packages = r2dii.utils::r2dii_packages()
    )
  )
}

r2dii_reference_package <- function(x, packages, url) {
  custom_table(
    reference_package(
      x, url = url, packages = packages
    )
  )
}

custom_table <- function(x) {
  x %>% 
    select(-package, -concept) %>% 
    unique() %>%
    knitr::kable(
      x, 
      format = "html",
      col.names = NULL,
      escape = FALSE
    ) %>%
    kableExtra::column_spec(1, bold = TRUE) %>% 
    kableExtra::column_spec(2, width = "20em")
}

describe_package <- function(package, url = r2dii_url) {
  # url has a trailing "/"
  link <- glue::glue("<a href={url}{package}>{package}</a>")
  title <- utils::packageDescription(package, fields = "Title")
  glue::glue("{link}: {title}")
}
```

### Global search

```{r global-search, warning=FALSE}
search_default <- "dataset"

bank_packages %>% 
  purrr::map_dfr(reference_package, url = r2dii_url) %>% 
  select(-package, -concept) %>% 
  unique() %>% 
  purrr::set_names(c("", "object", "description")) %>% 
  DT::datatable(
    escape = FALSE,
    rownames = NULL,
    options = list(
      # f: filter, t: table, i: information
      dom = "fti",
      search = list(search = search_default)
    )
  )
```

### `r describe_package(bank_packages[[1]])`

```{r package-1}
r2dii_reference_package(bank_packages[[1]], bank_packages, r2dii_url)
```

### `r describe_package(bank_packages[[2]])`

```{r package-2}
r2dii_reference_package(bank_packages[[2]], bank_packages, r2dii_url)
```

### `r describe_package(bank_packages[[3]])`

```{r package-3}
r2dii_reference_package(bank_packages[[3]], bank_packages, r2dii_url)
```

